created frontend routes
ctc-uci/cell-dogs-frontend pull request #17
Opened 2022-11-17 00:24 UTC by orvielalz

2022-11-18 12:03 UTC, alanchangxyz requested changes
just a few changes needed 👍

2022-11-18 12:03 UTC, alanchangxyz commented on src/App.jsx
> +// import logo from './logo.svg';
let's get rid of the default react logo if we don't need it anymore (the file, and this commented out import)

2022-11-18 12:03 UTC, alanchangxyz commented on src/App.jsx
>  import './App.css';
usually would prefer to import stuff in this order: modules, components, styles; also, if `App.css` isn't being used let's not import it (can just comment this out for now)

2022-11-18 12:03 UTC, alanchangxyz commented on src/App.jsx
> +        <Route path="*" render={() => ''} />
let's add a todo comment before this line to link the 404 page once this is merged

2022-11-18 12:03 UTC, alanchangxyz commented on src/components/Location.jsx
> +function Location() {
arrow function components instead of `function` components pls

```JavaScript
const Location = () => {
    ...
};
```

2022-11-18 12:03 UTC, alanchangxyz commented on src/App.jsx
> +        <Route path="/forgot" render={() => <Forgot />} />
i think for the Forgot Password page we can afford to make it `/forgot-password`, `/forgot` isn't exactly fully descriptive of what that page does

2022-11-18 12:03 UTC, alanchangxyz commented on src/App.jsx
> +import Forgot from './pages/Forgot';
[same as route] we can probably afford to make this `ForgotPassword` instead of `Forgot` to make it more descriptive of what it does

2022-11-18 23:34 UTC, claudeisakeeb requested changes
Looks great so far good job!

I know these routes were implemented with React Router V5 but could we actually implement this with React Router V6? Among other things V6 offers less memory usage, faster loading times, and better route matching (Read more [here](https://dev.to/narendersaini32/what-s-new-in-react-router-v6-2g8g#:~:text=The%20biggest%20thing%20we%20can,have%20size%20only%202.9kb)).

Basically you'd just have to reinstall `react-router-dom` (You can see how in the article) and then replace Switch with Routes and `render=...` with `component=...`. I think you will find that the result with V6 looks much more elegant. Please let Alan or I know if you need help or get stuck with anything.

2022-11-18 23:34 UTC, claudeisakeeb commented on src/App.jsx
> +    <div>
Can you please change this dev to a React fragment? That way styling doesn't get messed up because divs have default styling. Basically you can just replace <div> with <>

2022-11-18 23:34 UTC, claudeisakeeb commented on src/pages/AddDog.jsx
> +import React from 'react';
Could you actually please move all of the pages into directories with the same name? ie AddDog.jsx would go into a directory called AddDog, Dogs.jsx would go into a directory called Dogs, etc. This is because these pages will 99.999% end up with css files so we might as well take care of that in this task lol. If you want you can create the CSS files too :)
In the case that you do please use module.css (name the file AddDog.module.css as opposed to AddDog.css, etc.)

2022-11-20 22:05 UTC, orvielalz commented
> 
Hello! I tried following the article and I ran into an error:
Compiled with problems:X

ERROR in ./node_modules/react-router-dom/esm/react-router-dom.js

Module build failed (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Error: ENOENT: no such file or directory, open 'C:\Users\User\Documents\GitHub\ctc-uci\cell-dogs-frontend\node_modules\react-router-dom\esm\react-router-dom.js'

2022-11-20 22:43 UTC, claudeisakeeb requested changes
Great job! Just a few minor comments and this should be good.

For future sprints can y'all make your PRs with the /pr command and fill out the autogenerated template? You don't have to do that for this one but as tasks get bigger the template makes it easier for the reviewers :)

2022-11-20 22:43 UTC, claudeisakeeb commented on src/App.jsx
> +  const location = useLocation();
Since we're not using useLocation for anything we can just delete this for now unless I'm missing something?

2022-11-20 22:43 UTC, claudeisakeeb commented on src/App.jsx
> +  const location = useLocation();
You can just make Routes have no props :) ie remove key=... and location=...

2022-11-20 22:43 UTC, claudeisakeeb commented on src/App.jsx
> +        <Route path="*" element="" />
Hmmm since this is here let's move the TODO comment on line 18 to above line 22 and change it so that it's more clear what to do for the 404 team when they have to resolve merge conflicts. You can just say something like TODO: replace element with 404 page.

2022-11-20 22:43 UTC, claudeisakeeb commented on src/App.jsx
> +        <Route path="/dogs" element={<Dogs />} />
Since the landing page is going to be the doggo page lets just make this path="/"

2022-11-20 22:43 UTC, claudeisakeeb commented on src/components/Location.jsx
> +import React from 'react';
nice

2022-11-20 22:43 UTC, claudeisakeeb commented on src/App.jsx
> +    <>
I think you can safely delete this unnecessary React Fragment (along with its closing tag) because everything is contained in <Routes>

2022-11-20 23:53 UTC, claudeisakeeb submitted a review, later dismissed
lets get this money

2023-01-05 19:36 UTC, Madhu2244 approved these changes

2023-01-05 19:39 UTC, merged